config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  def markdown_content
    Kramdown::Document.new(content).to_html.html_safe
  end

  enum category: [:privacy, :security, :liability, :laws, :contracts, :crypto]
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @articles = Article.where("title ILIKE ?", "%#{params[:query]}%")
        .or(Article.where("content ILIKE ?", "%#{params[:query]}%"))
    elsif params[:filter_by].present?
      @articles = Article.where(category: params[:filter_by])
    else
      @articles = Article.all
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
    # @category = Category.new
    @categories = Article.categories
  end

  def edit
    @article = Article.find(params[:id])
    @categories = Article.categories
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :url, :category)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_controller_helper.rb
module CategoriesControllerHelper
end

app/views/application/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert fade in">
    <%= message %>
  </div>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="new-article">
      <h4><%= link_to articles_path do %>The DAO Book //<% end %></h4>
    </div>
    <div class="new-article">
      <h4><%= link_to new_article_path do %>New Article<% end %></h4>
    </div>

      <div class="new-article">
      <h4><%= link_to categories_path do %>Categories<% end %></h4>
    </div>

    <div class="new-article">
      <h4><%= link_to new_article_path do %>Resources<% end %></h4>
    </div>
</nav>

app/views/articles/_form.html.erb
<div class="newer-container">
    <%= simple_form_for @article do |f| %>
    <%= f.error_notification %>

    <h4><strong>
    <%= f.input :category_id, collection: @category.keys %>
    </strong></h4>

    <h4><strong>
    <%= f.input :title, placeholder: "Article title", :label_html => { :class => "label-css"} %>
    </strong></h4>

    <h4><strong>
    <%= f.input :url, as: :url %>
    </strong></h4>

    <h4><strong>
    <%= f.input :content, data: { editor: 'markdown' }, rows: 10 %>
    </strong></h4>

    <%= f.submit 'Save Article', class: "button" %>

  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<hr>

<h4>
  <button type="button" class="button">
    <%= link_to 'Show', @article %>
  </button>

  <button type="button" class="button">
    <%= link_to 'Back', articles_path %>
  </button>
</h4>

app/views/articles/index.html.erb
<div class="article-box">
  <% @articles.each do |article| %>
    <article class="index-article">
      <h3 class="title"><%= link_to article.title, article %></h3>
      <p><%= article.content[0..200]%>...</p>
        <p class="read"><%= link_to "> Read", article %></p>
    </article>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<hr>

<h4>
  <button type="button" class="button">
    <%= link_to 'Back', articles_path %>
  </button>
</h4>

app/views/articles/show.html.erb
<h4>
  <button type="button" class="button">
    <%= link_to articles_path do %>Home<% end %>
  </button>
</h4>

<% content_for(:title) do %>
  DAO_BOOK - <%= @article.title %>
<% end %>

<article class="article-show">
  <h1>
    <%= @article.title %>
  </h1>

<div class="link-box">
  <h4>
    <button type="button" class="button">
      <%= link_to edit_article_path(@article) do %>Edit<% end %>
    </button>
    <button type="button" class="button">
      <%= link_to @article.url, target: :_blank do %>Link<% end %>
    </button>
    <button type="button" class="button">
      <%= link_to article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } do %>Delete<% end %>
    </button>
  </h4>
</div>

<hr>

<div class="category-box">

</div>

<hr>
  <%= @article.markdown_content %>
</article>

<hr>

<h4>
  <button type="button" class="button">
      <%= link_to articles_path do %>Back<% end %>
  </button>
</h4>

app/views/categories/_form.html.erb
<%= simple_form_for [@category] do |f| %>
  <%= f.text_field :name %>
  <%= f.submit 'Save Category', class: "button btn-sm" %>
<% end %>

app/views/categories/index.html.erb
<div class="container cat-box">
  <% @categories.each do |category| %>
    <article class="index-category">
      <h4 class="title"><%= link_to category.name, category %></h4>
    </article>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<hr>

<h4>
  <button type="button" class="button">
    <%= link_to 'Back', articles_path %>
  </button>

  <button type="button" class="button">
    <%= link_to 'All categories', categories_path %>
  </button>
</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Wikinimous" %></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300|Roboto+Slab">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'navbar' %>

  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <%= render "flash" %>

        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>